// Edit kontak — lead, pelanggan, kontak WA, kontak percakapan inbox.
export const CONTACT_EDIT = {
  leadBtn: "lead-edit-btn",
  leadDialog: "lead-edit-dialog",
  leadName: "lead-edit-name",
  leadPhone: "lead-edit-phone",
  leadEmail: "lead-edit-email",
  leadSource: "lead-edit-source",
  leadPartner: "lead-edit-partner",
  leadUnitType: "lead-edit-unit-type",
  leadNotes: "lead-edit-notes",
  leadSubmit: "lead-edit-submit",
  customerBtn: "customer-edit-btn",
  customerDialog: "customer-edit-dialog",
  customerSubmit: "customer-edit-submit",
  waBtn: "wa-contact-edit-btn",
  waDialog: "wa-contact-edit-dialog",
  waName: "wa-contact-edit-name",
  waPhone: "wa-contact-edit-phone",
  waEmail: "wa-contact-edit-email",
  waMessage: "wa-contact-edit-message",
  waNotes: "wa-contact-edit-notes",
  waOptOut: "wa-contact-edit-optout",
  waSubmit: "wa-contact-edit-submit",
  inboxBtn: "inbox-contact-edit-btn",
  inboxDialog: "inbox-contact-edit-dialog",
  inboxName: "inbox-contact-edit-name",
  inboxPhone: "inbox-contact-edit-phone",
  inboxSubmit: "inbox-contact-edit-submit",
};
