export const DEAL_CANCEL = {
  btn: "deal-cancel-button",
  dialog: "deal-cancel-dialog",
  blocked: "deal-cancel-blocked",
  reason: "deal-cancel-reason",
  modeFull: "deal-cancel-mode-full",
  modePartial: "deal-cancel-mode-partial",
  modeForfeit: "deal-cancel-mode-forfeit",
  amount: "deal-cancel-refund-amount",
  method: "deal-cancel-method",
  submit: "deal-cancel-submit",
  summary: "deal-cancel-summary",
};

export const FUNDREQ = {
  page: "fund-requests-page",
  summary: "fund-requests-summary",
  filterStatus: "fund-requests-status-filter",
  filterType: "fund-requests-type-filter",
  table: "fund-requests-table",
  row: "fund-request-row",
  empty: "fund-requests-empty",
  newBtn: "fund-request-new-button",
  dialog: "fund-request-dialog",
  type: "fund-request-type",
  title: "fund-request-title",
  amount: "fund-request-amount",
  category: "fund-request-category",
  urgency: "fund-request-urgency",
  project: "fund-request-project",
  date: "fund-request-date",
  payeeName: "fund-request-payee-name",
  payeeBank: "fund-request-payee-bank",
  payeeAccount: "fund-request-payee-account",
  note: "fund-request-note",
  submit: "fund-request-submit",
  detailBtn: "fund-request-detail-button",
  detailSheet: "fund-request-detail-sheet",
  approveBtn: "fund-request-approve-button",
  rejectBtn: "fund-request-reject-button",
  cancelBtn: "fund-request-cancel-button",
  disburseBtn: "fund-request-disburse-button",
  disburseDialog: "fund-request-disburse-dialog",
  disburseAmount: "fund-request-disburse-amount",
  disburseSource: "fund-request-disburse-source",
  disburseRef: "fund-request-disburse-ref",
  disburseSubmit: "fund-request-disburse-submit",
  settleBtn: "fund-request-settle-button",
  settleDialog: "fund-request-settle-dialog",
  settleAddItem: "fund-request-settle-add-item",
  settleSubmit: "fund-request-settle-submit",
};
